### ISSUE TITLE
Regarding MAKE.md plugin

### ISSUE THREAD

**Issue by JackieFuuu** [DarioCasciato/obsidian-auto-folder-collapse#1]
Folders do not auto-collapse efter installing MAKE.md plugin for better sorting of my folders. Can't find anything in the plugin that would interfere with the auto-collapse.

**Comment by DarioCasciato** [comment]
Hi Jackie, i think what you are addressing is the "Space" View in the make.md plugin if i'm not wrong? Becuase in the normal view there should be nothing that interferes with the plugin. I'm currently out of office, so i currently can't recreate the issue.
Give me some feedback and i will check as soon as im back!

Regards
Dario

**Comment by DarioCasciato** [comment]
Hi, this bug was fixed in the new Version. The new version is "1.2.0". Please update the plugin in obsidian to fix the error.

Regards
Dario
