### ISSUE TITLE
Slow startup times and laggy usage

### ISSUE THREAD

**Issue by SandmansDreams** [DarioCasciato/obsidian-auto-folder-collapse#4]
I love this plugin, but something in a recent update made it way slower for some reason. It takes 3,011ms to start up, which is about half of the community plugin startup time. It also seems to sometimes not work at all. Not really sure why that is but I hope it is fixable. I also found this error in the console. 

![image](https://github.com/user-attachments/assets/c20f8ee4-dd00-4779-9f28-1511bee1f099)
![image](https://github.com/user-attachments/assets/724963eb-49b5-4aae-9a4a-5516017b7ad0)

**Comment by DarioCasciato** [comment]
Hi @SandmansDreams, thanks for the good feedback!

Please try to update the plugin in obsidian. I see that you have installed the version v1.0.6. This week i made the update to version v1.1.2, which is now also compatible with the new obsidian version. 

1. Open settings in obsidian
2. Go to the community plugins Tab and click the button "check for updates"
3. After that, an update button should pop up for the plugin.

Please give a short feedback, if this solution helped.

Regards
Dario

**Comment by SandmansDreams** [comment]
Wow you really got it. Down to 1ms at the bottom of my plugins list!
![image](https://github.com/user-attachments/assets/b86b9122-9a73-46a3-a38f-016492359d49)
Still just as slow when in use when collapsing and opening folders unfortunately. However, this might be due to something on my end somehow, not 100% sure its the plugins fault.

**Comment by DarioCasciato** [comment]
Hi @SandmansDreams, glad that the update helped!
I haven't noticed/experienced any lags/slowdowns when collapsing a folder. Also made a couple of stress tests to check how much the plugin can handle.

I'll close this issue, but if the problem further persists, and you assume that it's the "auto folder collapse" plugins fault, do not hesitate to open an issue👍

Regards
Dario
