### ISSUE TITLE
Plugin not working on my Obsidian Version 1.7.7

### ISSUE THREAD

**Issue by philerck** [DarioCasciato/obsidian-auto-folder-collapse#6]
Today I installed the plugin on version 1.7.7 and it is not working. 

I disabled the plugin, restart and activate plugin again => not working.
Disabled other plugins => not working

Maybe the is error on my side but it would great if you could find time to check if it is the plugin.

Thanks

**Comment by DarioCasciato** [comment]
hi @philerck, thanks for the issue. i tested the plugin with the new obsidian version extensively, and it did work fine for me.
can you please check if you get any console errors in obsidian? you can open the console with the following shortcut: "CTRL + SHIFT + I".

Regards
Dario

**Comment by philerck** [comment]
Hi Dario, thanks for your help.

No errors in console. I uninstall the plugin and after reinstall I get this info:
Auto Folder Collapse: styles.css not found

Maybe thats my problem

Regards Phil

**Comment by DarioCasciato** [comment]
Hi @philerck 

Hmm sounds strange, since auto folder collapse does not use a styles.css in any form. It sounds like you are either using a plugin or a obsidian theme which is interfering with the plugin. Try to deactivate all plugins except auto folder collapse, switch to the normal theme and reload obsidian and try again.
And its very strange that the console is not giving you an error message, since after the install you get a error.

Try and let me know!

Regards
Dario

**Comment by philerck** [comment]
Hi @DarioCasciato ,

after that I get an error from auto-folder-collapse:

app.js:1 Obsidian Developer Console
plugin:auto-folder-collapse:8 Loading Auto Folder Collapse Plugin
plugin:auto-folder-collapse:42 File Explorer element not found. Retry 1/5 after 1000ms.
setupObserverWithRetries @ plugin:auto-folder-collapse:42
plugin:auto-folder-collapse:42 File Explorer element not found. Retry 2/5 after 1000ms.
setupObserverWithRetries @ plugin:auto-folder-collapse:42
plugin:auto-folder-collapse:42 File Explorer element not found. Retry 3/5 after 1000ms.
setupObserverWithRetries @ plugin:auto-folder-collapse:42
plugin:auto-folder-collapse:42 File Explorer element not found. Retry 4/5 after 1000ms.
setupObserverWithRetries @ plugin:auto-folder-collapse:42
plugin:auto-folder-collapse:42 File Explorer element not found. Retry 5/5 after 1000ms.
setupObserverWithRetries @ plugin:auto-folder-collapse:42
plugin:auto-folder-collapse:46 Auto Folder Collapse Plugin: File Explorer element not found after all retries.
setupObserverWithRetries @ plugin:auto-folder-collapse:46

All Plugins are deactivated and theme is normal.

Is that helping you? Thanks for you time

Regards Phil

**Comment by DarioCasciato** [comment]
Hi Phil, thanks for your test.
Could you check if you have the newest version of auto folder collapse installed?
Its the only thing that is coming to my mind at the moment. The plugin should work by itself without any other, this has been extensively tested.

Regards
Dario

**Comment by philerck** [comment]
Hi Dario,

thanks a lot for your help. I have the newest version and I will try to get it working.
Please close the issue. :-)

Best regards Phil

**Comment by eyssette** [comment]
> No errors in console. I uninstall the plugin and after reinstall I get this info:
> Auto Folder Collapse: styles.css not found

I had the same error : it's an incompatibility with the [style settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
